name: Build and push Docker image Back-End
on:  
  push:    
    branches:      
    - init-pipeline
jobs:  
  build-and-push:    
    runs-on: ubuntu-latest    
    steps:      
    - name: Checkout code        
      uses: actions/checkout@v2      
    - name: Build and push Docker image        
      uses: docker/build-push-action@v4        
      with:          
        context: ./learngithub          
        push: false          
        tags: your-dockerhub-username/your-image-name:latest
