name: Build and push Docker image Back-End and Front-end
on:  
  push:    
    branches:  
    - '**'
    - '!main'
  pull_request:
    branches:
      - main
jobs:  
  build:    
    runs-on: ubuntu-latest    
    steps:      
    - name: Checkout code        
      uses: actions/checkout@v2      
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image back-end        
      uses: docker/build-push-action@v4        
      with:          
        context: ./learngithub          
        push: false          
        tags: sample-image-back-end:v1
        outputs: type=docker,dest=/tmp/sample-image-back-end-v1.tar
        
    - name: Upload artifact back-end
      uses: actions/upload-artifact@v3
      with:
        name: sample-image-back-end
        path: /tmp/sample-image-back-end-v1.tar
    - name: Build Docker image front-end        
      uses: docker/build-push-action@v4        
      with:          
        context: ./front-end          
        push: false          
        tags: sample-image-front-end:v1
        outputs: type=docker,dest=/tmp/sample-image-front-end-v1.tar
        
    - name: Upload artifact front-end
      uses: actions/upload-artifact@v3
      with:
        name: sample-image-front-end
        path: /tmp/sample-image-front-end-v1.tar
      
  download-load-image-docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Download artifact front-end
        uses: actions/download-artifact@v3
        with:
          name: sample-image-front-end
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/sample-image-front-end-v1.tar
          docker image ls -a
      - name: Download artifact back-end
        uses: actions/download-artifact@v3
        with:
          name: sample-image-back-end
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/sample-image-back-end-v1.tar
          docker image ls -a
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker import image
        run: |
          docker load --input /tmp/sample-image-front-end-v1.tar
          docker image tag sample-image-front-end https://index.docker.io/v1/mogador26/sample-image-front-end:v1
          docker image push https://index.docker.io/v1/mogador26/sample-image-front-end:v1
              
     